const data = {
  title: "Dialog",
  default: [
    {
      titles: {
        dialog: "hggs-dialog hggs-dialog--big",
        header: "hggs-dialog-header",
        closeButton: "hggs-dialog-close hggs-button hggs-button--quaternary",
        closeIcon: "hggs-icon hggs-icon--close",
        body: "hggs-dialog-body",
        footer: "hggs-dialog-footer",
        actions: "hggs-dialog-actions",
        okButton: "hggs-button hggs-button--primary hggs-button--big",
      },
      ids: {
        dialog: ["dialog-big"],
        triggerButton: ["open-dialog-btn-big"],
        closeButton: ["close-dialog-btn-big"],
        okButton: ["ok-dialog-btn-big"],
      },
      styles: {
        titles: {
          dialog: titleStyles,
          header: titleIndentation1xStyles,
          closeButton: titleIndentation3xStyles,
          closeIcon: titleIndentation4xStyles,
          body: titleIndentation1xStyles,
          footer: titleIndentation1xStyles,
          actions: titleIndentation2xStyles,
          okButton: titleIndentation3xStyles,
        },
        article: articleStyles,
        header: headerStyles,
      },
      classes: {
        dialog: ["hggs-dialog", "hggs-dialog--big"],
        header: ["hggs-dialog-header"],
        closeButton: ["hggs-dialog-close", "hggs-button", "hggs-button--quaternary"],
        closeIcon: ["hggs-icon", "hggs-icon--close"],
        body: ["hggs-dialog-body"],
        footer: ["hggs-dialog-footer"],
        actions: ["hggs-dialog-actions"],
        triggerButton: ["hggs-button", "hggs-button--primary", "hggs-button--big"],
      },
      label: {
        triggerButton: "Big",
      },
    },
    {
      titles: {
        dialog: "hggs-dialog hggs-dialog--medium",
        header: "hggs-dialog-header",
        closeButton: "hggs-dialog-close hggs-button hggs-button--quaternary",
        closeIcon: "hggs-icon hggs-icon--close",
        body: "hggs-dialog-body",
        footer: "hggs-dialog-footer",
        actions: "hggs-dialog-actions",
        okButton: "hggs-button hggs-button--primary hggs-button--medium",
      },
      ids: {
        dialog: ["dialog-medium"],
        triggerButton: ["open-dialog-btn-medium"],
        closeButton: ["close-dialog-btn-medium"],
        okButton: ["ok-dialog-btn-medium"],
      },
      styles: {
        titles: {
          dialog: titleStyles,
          header: titleIndentation1xStyles,
          closeButton: titleIndentation3xStyles,
          closeIcon: titleIndentation4xStyles,
          body: titleIndentation1xStyles,
          footer: titleIndentation1xStyles,
          actions: titleIndentation2xStyles,
          okButton: titleIndentation3xStyles,
        },
        article: articleStyles,
        header: headerStyles,
      },
      classes: {
        dialog: ["hggs-dialog", "hggs-dialog--medium"],
        header: ["hggs-dialog-header"],
        closeButton: ["hggs-dialog-close", "hggs-button", "hggs-button--quaternary"],
        closeIcon: ["hggs-icon", "hggs-icon--close"],
        body: ["hggs-dialog-body"],
        footer: ["hggs-dialog-footer"],
        actions: ["hggs-dialog-actions"],
        triggerButton: ["hggs-button", "hggs-button--primary", "hggs-button--medium"],
      },
      label: {
        triggerButton: "Medium",
      },
    },
    {
      titles: {
        dialog: "hggs-dialog hggs-dialog--small",
        header: "hggs-dialog-header",
        closeButton: "hggs-dialog-close hggs-button hggs-button--quaternary",
        closeIcon: "hggs-icon hggs-icon--close",
        body: "hggs-dialog-body",
        footer: "hggs-dialog-footer",
        actions: "hggs-dialog-actions",
        okButton: "hggs-button hggs-button--primary hggs-button--small",
      },
      ids: {
        dialog: ["dialog-small"],
        triggerButton: ["open-dialog-btn-small"],
        closeButton: ["close-dialog-btn-small"],
        okButton: ["ok-dialog-btn-small"],
      },
      styles: {
        titles: {
          dialog: titleStyles,
          header: titleIndentation1xStyles,
          closeButton: titleIndentation3xStyles,
          closeIcon: titleIndentation4xStyles,
          body: titleIndentation1xStyles,
          footer: titleIndentation1xStyles,
          actions: titleIndentation2xStyles,
          okButton: titleIndentation3xStyles,
        },
        article: articleStyles,
        header: headerStyles,
      },
      classes: {
        dialog: ["hggs-dialog", "hggs-dialog--small"],
        header: ["hggs-dialog-header"],
        closeButton: ["hggs-dialog-close", "hggs-button", "hggs-button--quaternary"],
        closeIcon: ["hggs-icon", "hggs-icon--close"],
        body: ["hggs-dialog-body"],
        footer: ["hggs-dialog-footer"],
        actions: ["hggs-dialog-actions"],
        triggerButton: ["hggs-button", "hggs-button--primary", "hggs-button--small"],
      },
      label: {
        triggerButton: "Small",
      },
    },
  ],
};

export default data;
