const data = {
  title: "Steps",
  default: [
    {
      titles: {
        steps: "hggs-steps",
        step: "hggs-step hggs-step--divider hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "(hggs-step-divider)?",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps"],
        items: [
          {
            step: ["hggs-step", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--complete"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--error"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--waiting"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps",
        step: "hggs-step hggs-step--no-description hggs-step--divider hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "(hggs-step-divider)?",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps"],
        items: [
          {
            step: ["hggs-step", "hggs-step--no-description", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--no-description", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--no-description", "hggs-step--divider", "hggs-step--complete"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--no-description", "hggs-step--divider", "hggs-step--error"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--no-description", "hggs-step--waiting"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps",
        step: "hggs-step  hggs-step--small hggs-step--divider hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "(hggs-step-divider)?",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps"],
        items: [
          {
            step: ["hggs-step", "hggs-step--small", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--small", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--small", "hggs-step--divider", "hggs-step--complete"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--small", "hggs-step--divider", "hggs-step--error"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--small", "hggs-step--waiting"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps",
        step: "hggs-step hggs-step--small hggs-step--no-description hggs-step--divider hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "(hggs-step-divider)?",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps"],
        items: [
          {
            step: ["hggs-step", "hggs-step--small", "hggs-step--no-description", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--small", "hggs-step--no-description", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--small",
              "hggs-step--no-description",
              "hggs-step--divider",
              "hggs-step--complete",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--small",
              "hggs-step--no-description",
              "hggs-step--divider",
              "hggs-step--error",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--small", "hggs-step--no-description", "hggs-step--waiting"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps",
        step: "hggs-step hggs-step--dot hggs-step--divider hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "(hggs-step-divider)?",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps"],
        items: [
          {
            step: ["hggs-step", "hggs-step--dot", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--dot", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--dot", "hggs-step--divider", "hggs-step--complete"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--dot", "hggs-step--divider", "hggs-step--error"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--dot", "hggs-step--waiting"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps",
        step: "hggs-step hggs-step--dot hggs-step--no-description hggs-step--divider hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "(hggs-step-divider)?",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps"],
        items: [
          {
            step: ["hggs-step", "hggs-step--dot", "hggs-step--no-description", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--dot", "hggs-step--no-description", "hggs-step--divider"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--dot",
              "hggs-step--no-description",
              "hggs-step--divider",
              "hggs-step--complete",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--dot",
              "hggs-step--no-description",
              "hggs-step--divider",
              "hggs-step--error",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--dot", "hggs-step--no-description", "hggs-step--waiting"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
  ],
  vertical: [
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--divider hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--complete", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--error", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--waiting", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--divider hggs-step--small hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})? (hggs-icon--small)?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--complete", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--error", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--waiting", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--divider hggs-step--no-description hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--no-description", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--divider", "hggs-step--no-description", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--complete",
              "hggs-step--vertical",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--error",
              "hggs-step--vertical",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--waiting", "hggs-step--no-description", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--divider hggs-step--no-description hggs-step--small hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})? hggs-icon--small",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--vertical",
              "hggs-step--small",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--vertical",
              "hggs-step--small",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--complete",
              "hggs-step--vertical",
              "hggs-step--small",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--error",
              "hggs-step--vertical",
              "hggs-step--small",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--waiting",
              "hggs-step--no-description",
              "hggs-step--vertical",
              "hggs-step--small",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--divider hggs-step--no-description hggs-step--dot hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--vertical",
              "hggs-step--dot",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--vertical",
              "hggs-step--dot",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--complete",
              "hggs-step--vertical",
              "hggs-step--dot",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--divider",
              "hggs-step--no-description",
              "hggs-step--error",
              "hggs-step--vertical",
              "hggs-step--dot",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--waiting",
              "hggs-step--no-description",
              "hggs-step--vertical",
              "hggs-step--dot",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: ["hggs-step", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--complete", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--error", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--waiting", "hggs-step--vertical"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--no-description hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--no-description"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--no-description"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--complete", "hggs-step--vertical", "hggs-step--no-description"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--error", "hggs-step--vertical", "hggs-step--no-description"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--waiting", "hggs-step--vertical", "hggs-step--no-description"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--small hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--complete", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--error", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--waiting", "hggs-step--vertical", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--small hggs-step--no-description hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        reference: "(hggs-step-reference)? (hggs-icon hggs-icon--{type} hggs-icon--{variant})?",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          reference: titleIndentation4xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--no-description", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--no-description", "hggs-step--small"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--complete",
              "hggs-step--no-description",
              "hggs-step--vertical",
              "hggs-step--small",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--error",
              "hggs-step--no-description",
              "hggs-step--vertical",
              "hggs-step--small",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--waiting",
              "hggs-step--no-description",
              "hggs-step--vertical",
              "hggs-step--small",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step-dot hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--dot"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--dot"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--complete", "hggs-step--vertical", "hggs-step--dot"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--error", "hggs-step--vertical", "hggs-step--dot"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--waiting", "hggs-step--vertical", "hggs-step--dot"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
    {
      titles: {
        steps: "hggs-steps hggs-steps--vertical",
        step: "hggs-step hggs-step--vertical hggs-step--no-description hggs-step--dot hggs-step--{state})?",
        side: "hggs-step-side",
        signal: "hggs-step-signal",
        body: "hggs-step-body",
        main: "hggs-step-main",
        title: "hggs-step-title",
        divider: "hggs-step-divider",
        description: "hggs-step-description",
      },
      styles: {
        header: headerStyles,
        article: [...articleStyles],
        titles: {
          steps: titleStyles,
          step: titleIndentation1xStyles,
          side: titleIndentation2xStyles,
          signal: titleIndentation3xStyles,
          body: titleIndentation2xStyles,
          main: titleIndentation3xStyles,
          title: titleIndentation4xStyles,
          divider: titleIndentation4xStyles,
          description: titleIndentation3xStyles,
        },
      },
      classes: {
        steps: ["hggs-steps", "hggs-steps--vertical"],
        items: [
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--no-description", "hggs-step--dot"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: ["hggs-step", "hggs-step--vertical", "hggs-step--no-description", "hggs-step--dot"],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            reference: ["hggs-step-reference"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--complete",
              "hggs-step--vertical",
              "hggs-step--no-description",
              "hggs-step--dot",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--check", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--error",
              "hggs-step--vertical",
              "hggs-step--no-description",
              "hggs-step--dot",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--close", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            divider: ["hggs-step-divider"],
            description: ["hggs-step-description"],
          },
          {
            step: [
              "hggs-step",
              "hggs-step--waiting",
              "hggs-step--vertical",
              "hggs-step--no-description",
              "hggs-step--dot",
            ],
            side: ["hggs-step-side"],
            signal: ["hggs-step-signal"],
            icon: ["hggs-icon", "hggs-icon--pending", "hggs-icon--quinary", "hggs-icon--small"],
            body: ["hggs-step-body"],
            main: ["hggs-step-main"],
            title: ["hggs-step-title"],
            description: ["hggs-step-description"],
          },
        ],
      },
      labels: {
        items: [
          {
            title: "Personal data",
            description: "Set your personal data",
            side: "1",
          },
          {
            title: "Financial data",
            description: "Set your financial data",
            side: "2",
          },
          {
            title: "Terms and conditions",
            description: "Read and sign terms and conditions",
            complete: true,
          },
          {
            title: "Summary",
            description: "This step contains errors that you need to fix",
            error: true,
          },
          {
            title: "Payment",
            description: "Waiting...",
            waiting: true,
          },
        ],
      },
    },
  ],
};

export default data;
